laserMapping:
  ros__parameters:
    common:
      lid_topic: "/lidar_points"
      imu_topic: "/lidar_imu"
      time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

    preprocess:
      lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for JT16
      scan_line: 16
      blind: 2.0
      time_scale: 0.001            # 1e-3 expressed as decimal for YAML clarity

    mapping:
      acc_cov: 0.01
      gyr_cov: 0.01
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 360
      det_range: 50.0
      extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic
      extrinsic_T: [0.0, 0.0, 0.0]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]

    publish:
      path_publish_en: false
      scan_publish_en: true       # false: close all the point cloud output
      scan_effect_pub_en: true    # true: publish the pointscloud of effect point
      dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
      scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

    path_save_en: true                 # 保存轨迹，用于精度计算和比较

    pcd_save:
      pcd_save_en: true
      interval: -1                 # how many LiDAR frames saved in each pcd file;
                                  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

    feature_extract_enable: false
    point_filter_num: 1
    max_iteration: 3
    filter_size_surf: 0.5
    filter_size_map: 0.5             # 暂时未用到，代码中为0， 即倾向于将降采样后的scan中的所有点加入map
    cube_side_length: 1000.0

    ivox_grid_resolution: 0.5        # default=0.2
    ivox_nearby_type: 18             # 6, 18, 26
    esti_plane_threshold: 0.1        # default=0.1
