common:
  lid_topic: "/rslidar_points"
  imu_topic: "/rslidar_imu_data"
  time_sync_en: false # ONLY turn on when external time synchronization is really not possible

preprocess:
  lidar_type: 5 # 1->Livox, 2->Velodyne, 3->Ouster, 4->Hesai, 5->Robosense
  scan_line: 96
  blind: 0.5

mapping:
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  fov_degree: 180
  det_range: 100.0
  extrinsic_est_en: true # true: enable the online estimation of IMU-LiDAR extrinsic
  extrinsic_T: [0, 0, 0]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]

publish:
  path_publish_en: true
  scan_publish_en: true # false: close all the point cloud output
  scan_effect_pub_en: false # true: publish the pointscloud of effect point
  dense_publish_en: false # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: true # true: output the point cloud scans in IMU-body-frame

path_save_en: false # 保存轨迹，用于精度计算和比较

pcd_save:
  pcd_save_en: true
  interval: -1 # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

feature_extract_enable: false
point_filter_num: 3
max_iteration: 3
filter_size_surf: 0.1
filter_size_map: 0.3
cube_side_length: 1000

ivox_grid_resolution: 0.2 # default=0.2
ivox_nearby_type: 18 # 6, 18, 26
esti_plane_threshold: 0.1 # default=0.1
